[ULC] added file completion after :load commands
lukeg101/lplzoo pull request #8
Opened 2019-07-15 05:13 UTC by colmbaston

2019-07-15 09:04 UTC, colmbaston commented
**TODO**:

- Use `" ()λ\\."` as word separators in tab-completion for terms, but only use `" "` for filepaths.
- Parsing and printing filepaths with escape characters in a platform-independent way.

2019-07-19 23:37 UTC, lukeg101 requested changes
This is very good, comments inlined.
Some of the recent changes to ULC have adopted a long line length, I follow the belief that lines should be around [80 columns in width ](https://softwareengineering.stackexchange.com/questions/148677/why-is-80-characters-the-standard-limit-for-code-width).
Please can you ensure that all Haskell files in ULC adopt this convention (80 chars or less). This is mostly due to the Parser changes but for uniformity it would be nice if all of ULC followed this convention

2019-07-19 23:37 UTC, lukeg101 commented on ULC/Repl.hs
>      contextCompletion :: CompletionFunc (StateT Environment IO)
can you add a quick comment for each of these please, it will help those who see this in the future

2019-07-19 23:37 UTC, lukeg101 commented on ULC/Parser.hs
> +pCommand = spaces (pReds +++ pLet +++ pLoad +++ (T <$> pTerm) +++ pComment)
why do you declare pReds but not `T <$> pTerm`?
For uniformity this would look better

2019-07-19 23:37 UTC, lukeg101 commented on ULC/Repl.hs
> +                            else map (\x -> Completion x x True) . filter (xs `isPrefixOf`) . (if all isSpace prev then (comms ++) else id) . M.keys <$> get
This is quite the long line, please can you split this up into something shorter

2019-08-11 18:25 UTC, closed without merging